In [3]:
from IPython.display import display
from IPython.display import HTML
import IPython.core.display as di # Example: di.display_html('<h3>%s:</h3>' % str, raw=True)

# This line will hide code by default when the notebook is exported as HTML
di.display_html('<script>jQuery(function() {if (jQuery("body.notebook_app").length == 0) { jQuery(".input_area").toggle(); jQuery(".prompt").toggle();}});</script>', raw=True)

# This line will add a button to toggle visibility of code blocks, for use with the HTML export version
di.display_html('''<button onclick="jQuery('.input_area').toggle(); jQuery('.prompt').toggle();">Toggle code</button>''', raw=True)

Toggle code

In [4]:
###### Test if your notebook works

hello world


In [5]:
print("hello world")

hello world


In [6]:
###### Import libraries

In [8]:
import numpy as np
import pandas as pd
import scipy

In [9]:
###### Variables

In [11]:
# number
x = 5 
y = 6
print(x + y)

#string
my_string ="python"
print(my_string)

11
python


In [12]:
###### String Operation

In [23]:
# Length of a string
len(my_string)

# concatenation
print("my " + my_string)

# coercion
print("my " + my_string + " is level " + str(x))

# visit a character: 0-index
my_string[3]
my_string[-1]

# string manipulations
my_string.upper()
my_string.replace("y", "yyyy")
my_string.find("y")


my python
my python is level 5


1

In [24]:
###### List

In [30]:
colors = ["red", "blue", "green"]
#print(colors)
#print(colors[0])
#print(len(colors))

# manipulation
# append at the bottom
colors.append("yellow")
print(colors)

# insert at any position
colors.insert(1, "pink")
print(colors)

# remove an element
colors.pop(1)
print(colors)

# search for an element
colors.index("green")

# quiz: what if there's duplicate
colors = ["red", "blue", "blue", "green"]
colors.index("blue")

# quiz: what about other stuff? remove duplicate?
# answer: use numpy which handles this type of stuff

['red', 'blue', 'green', 'yellow']
['red', 'pink', 'blue', 'green', 'yellow']
['red', 'blue', 'green', 'yellow']


1

In [31]:
###### control flow

In [32]:
# if/else. simple example
x = 10
if x == 5:
    print("Yes")
else:
    print("No")

No


In [35]:
# if/else. complex example
speed = 82
mood = "bad"

if speed >= 80:
    print ("License and registration please")
    if mood == 'terrible' or speed >= 100:
        print ("You have the right to remain silent.")
    elif mood == 'bad' or speed >= 90:
        print ("I'm going to have to write you a ticket.")
    else:
        print ("Let's try to keep it under 80 ok?")

License and registration please
I'm going to have to write you a ticket.


In [36]:
# for loop
primes = [2, 3, 5, 7]
for prime in primes:
    print(prime)

2
3
5
7


In [37]:
# tuple
my_tuple = ("price", 5.7)
print(len(my_tuple))
print(my_tuple[1])

2
5.7


In [38]:
###### numpy

In [70]:
# create a column vector
col_vec = np.array([[1], [2]])
print (col_vec)

# create a row vector
row_vec = np.array([[1, 2]])
print (row_vec)

# create a matrix
my_matrix = np.array([[1, 2], [3, 4]])
print (my_matrix)

# inspect dimensions
shape = my_matrix.shape
print ("matrix rows", shape[0], "columns", shape[1])
    
# transpose
my_matrix_t = my_matrix.transpose()
print ("transposed matrix")
print (my_matrix_t)

# matrix calculation
# addition
a = np.array([[1, 2], [3, 4]])
b = np.array([[1, 2], [3, 4]])
print ("a + b")
print (a + b)

# matrix product
print ("matrix product")
print (np.dot(a, b))


# more interesting stuff:
# on 1d array, which is essentially a list.
my_array = np.array([1, 2, 3, 4])
len(my_array)
my_array.sum()
my_array.max()
my_array.mean()

# quiz:
my_array = np.array([1, 2, 2, 4, 5])
np.unique(my_array)

# other stuff:
# subset
my_array[-1]
my_array[my_array>2]

# add/remove element
np.append(my_array, 6)
np.insert(my_array, 3, 3)
np.delete(my_array, [1])


[[1]
 [2]]
[[1 2]]
[[1 2]
 [3 4]]
matrix rows 2 columns 2
transposed matrix
[[1 3]
 [2 4]]
a + b
[[2 4]
 [6 8]]
matrix product
[[ 7 10]
 [15 22]]


AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [71]:
###### pandas

In [72]:
###### pandas basic

In [81]:
df = pd.DataFrame(
    {
        "customer_id": ["A", "B", "C"],
        "date": ["5/1/2017", "5/8/2017", "5/11/2017"],
        "spend": [10, 5, 20]
    },
    #index = [1, 2, 3],
    columns = ["customer_id", "date", "spend"]
)
print(df)
# describe table
df.shape

# subset columns
df["spend"]
df[["customer_id", "spend"]]

# subset rows
df.sample(n = 1)
df.head(n = 1)

  customer_id       date  spend
0           A   5/1/2017     10
1           B   5/8/2017      5
2           C  5/11/2017     20


customer_id      date  spend
0           A  5/1/2017     10

In [ ]:
###### pandas data I/O

In [ ]:
# from csv
file_location = "/Users/mingchang/Downloads/"
file_name = "BA501_python_data.csv"
my_data = pd.read_csv(file_location + file_name)

my_data.head(5)